name: Bug Report
description: Melde einen Fehler, den du gefunden hast
title: "[BUG] Titel des Fehlers hier"
labels: [bug]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Danke, dass du einen Fehler meldest! Bitte fülle die folgenden Felder aus, damit wir den Fehler reproduzieren und beheben können.

  - type: input
    id: description
    attributes:
      label: Beschreibung des Fehlers
      description: Eine kurze, prägnante Beschreibung des Fehlers.
      placeholder: Der Fehler ist...

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Schritte zum Reproduzieren
      description: Schritt-für-Schritt-Anleitung, um den Fehler zu reproduzieren.
      placeholder: |
        1. Gehe zu '...'
        2. Klicke auf '...'
        3. Scrolle herunter zu '...'
        4. Fehler tritt auf

  - type: input
    id: expected_behavior
    attributes:
      label: Erwartetes Verhalten
      description: Eine klare und prägnante Beschreibung dessen, was du erwartet hast, dass passiert.
      placeholder: Ich erwartete...

  - type: input
    id: actual_behavior
    attributes:
      label: Aktuelles Verhalten
      description: Was tatsächlich passiert ist, einschließlich einer fehlerhaften Ausgabe, Fehlermeldungen oder Verhaltensweisen.
      placeholder: Tatsächlich passierte...

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Wenn möglich, füge Screenshots hinzu, um den Fehler zu erklären.
      placeholder: URL zu Screenshots...

  - type: input
    id: environment
    attributes:
      label: Umgebung
      description: Betriebssystem, Browser und Version, die verwendet werden.
      placeholder: |
        - Betriebssystem: [z.B. Windows 10, macOS Mojave, Linux Ubuntu 20.04]
        - Browser: [z.B. Chrome, Firefox, Safari]
        - Version: [z.B. 1.2.3]

  - type: textarea
    id: additional_information
    attributes:
      label: Zusätzliche Informationen
      description: Jegliche zusätzlichen Informationen oder Kontext zum Problem hier.
      placeholder: Zusätzliche Informationen...
