name: Bug Report
description: Melde einen Fehler, den du gefunden hast
title: "[BUG] Titel des Fehlers hier"
labels: [bug]
assignees: [hennycraft52]

body:
  - type: markdown
    attributes:
      value: |
        Danke, dass du einen Fehler meldest! Bitte fülle die folgenden Felder aus, damit wir den Fehler reproduzieren und beheben können.

  - type: input
    id: description
    attributes:
      label: Beschreibung der Anfrage
      description: Eine kurze, prägnante Beschreibung der Anfrage.
      placeholder: Das Problem ist...
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Wenn möglich, füge Screenshots hinzu, um das Problem zu erklären.
      placeholder: URL zu Screenshots...


  - type: textarea
    id: additional_information
    attributes:
      label: Zusätzliche Informationen
      description: Jegliche zusätzlichen Informationen oder Kontext zum Problem hier.
      placeholder: Zusätzliche Informationen...
